name: Copy and Rename Files on Push

# trigger master 브랜치에 push 할 때 해당 workflows를 실행
on:
  push:
    branches:
      - master

# workflows 내부의 job들 각 job은 하나의 트랜잭션
jobs:
  copy_files:
    # 실행시키는 환경. 대규모 프로젝트면 프로젝트환경과 맞추기도 한다.
    runs-on: ubuntu-latest



    # job 내 프로젝트 하나의 steps는 하나의 트랜잭션안에 있어서 하나가 실패하면 전체 취소
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # 전체 커밋 기록을 가져오기
                          # 디폴트가 현재 커밋이라 설정 안하면 HEAD^ 못가져옴. 

    # 한글 깨짐 수정
      - name: Set Git config to handle Korean filenames
        run: |
          git config --global core.quotepath false
      - name: Set UTF-8 locale
        run: |
          sudo update-locale LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8

    # github action의 보안관련 설정
      - name: Set safe directory for Git
        run: |
          git config --global --add safe.directory /github/workspace

    # 유저 적용
      - name: Set up Git
        run: |
          git config --global user.name 'rn0614'
          git config --global user.email 'rn0614@naver.com'

    # 파일 copy & 이름변경 로직
      - name: Copy and Rename Files
        run: |
          # 플래그 변수 초기화
          FILE_COPIED=false

          # 오늘 날짜 형식 (YYYY-MM-DD)
          TODAY=$(date +"%Y-%m-%d")

          # 시작부분 로그 
          echo "변경파일 추출 시작"

          # 변경된 .md 파일 목록을 확인하기 위해 diff_output.txt에 저장
          git diff --name-only HEAD^ HEAD > diff_output.txt
          cat diff_output.txt  # 변경된 파일 목록 출력

          # 파일 목록에서 한 줄씩 파일명을 읽어오기
          cat diff_output.txt | while read FILE; do
            echo "FILE 경로: ${FILE}"

            # 파일명을 얻음
            FILENAME=$(basename "$FILE" .md)

            # 파일명에서 공백을 '_'로 대체
            FILENAME_WITH_UNDERSCORES=$(echo "$FILENAME" | sed 's/ /_/g')

            # 새로운 파일명 생성 (YYYY-MM-DD-파일명.md)
            NEW_FILENAME="${TODAY}-${FILENAME_WITH_UNDERSCORES}.md"

            # 이름 formatting 완료된 파일이름 리스트 출력
            echo "COPIED_FILENAME : ${NEW_FILENAME}"

            # _posts 폴더로 파일 복사 및 파일명 변경
            cp "$FILE" "_posts/${NEW_FILENAME}"

            # 파일 복사 발생 시 플래그 변경
            FILE_COPIED=true
          done

          # 플래그 값 출력 (커밋 단계에서 사용하기 위해 환경 변수로 설정)
          echo "file_copied=${FILE_COPIED}" >> $GITHUB_ENV

          # 환경 변수 $GITHUB_ENV와 로컬 변수 FILE_COPIED 값 출력
          echo "GITHUB_ENV 설정 완료. 파일 복사 여부: ${FILE_COPIED}"
          echo "현재 GITHUB_ENV 내용:"
          cat $GITHUB_ENV
      # 변경점 psuh
      - name: Commit and Push Changes
        run: |
          # GitHub Actions 환경 변수 참조
          echo "file_copied is: $file_copied"
          # 파일이 복사된 경우에만 커밋 및 푸시
          if [ "$file_copied" = "true" ]; then
            git add _posts/*.md
            git commit -m "Copy and rename files on push"
            git push origin master
          else
            echo "No files were copied. Skipping commit."
          fi