name: Move and Rename Files on Push

# push 이벤트가 발생할 때 실행
on:
  push:
    branches:
      - master  # master 브랜치에 푸시할 때 실행

jobs:
  move_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set Safe Directory for _github_open
        run: git config --global --add safe.directory /github/workspace/_github_open

      - name: Set Safe Directory for _posts
        run: git config --global --add safe.directory /github/workspace/_posts

      - name: Set up Git
        run: |
          git config --global user.name 'rn0614'
          git config --global user.email 'rn0614@naver.com'

      - name: Move and Rename Files
        run: |
          # 오늘 날짜 형식 (YYYY-MM-DD)
          TODAY=$(date +"%Y-%m-%d")

          # git diff를 통해 이번 커밋에서 변경된 .md 파일 목록 가져오기
          git diff --name-only HEAD^ HEAD | grep '^_github_open/.*\.md$' | while read FILE; do
            FILENAME=$(basename "$FILE" .md)  # 확장자 제거한 파일명
            
            # 파일명에서 공백을 '_'로 대체
            FILENAME_WITH_UNDERSCORES=$(echo "$FILENAME" | sed 's/ /_/g')
            
            # 새로운 파일명 생성 (YYYY-MM-DD-파일명.md)
            NEW_FILENAME="${TODAY}-${FILENAME_WITH_UNDERSCORES}.md"

            # _posts 폴더로 파일 이동 및 파일명 변경
            mv "$FILE" "_posts/${NEW_FILENAME}"
          done

      - name: Commit and Push Changes
        run: |
          git add _posts/*.md
          git commit -m "Move and rename files on push"
          git push origin master  # 'master' 브랜치로 변경 사항 푸시
